# Generated by Django 3.2 on 2022-04-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
