# Generated by Django 3.2 on 2022-05-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220426_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.TextField(blank=True, default=False, null=True),
        ),
    ]
